# Generated by Django 2.2.2 on 2019-09-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='manager',
        ),
    ]
